### PR TITLE
fix comparator interaction

### LINKED ISSUE #2102: Crash on comparator placement.
The game crashes when a comparator is placed next to an altar when a bloodstone block is underneath it.  The problem has been speculated to be this line:

"return NetworkHelper.getSoulNetwork(binding).getCurrentEssence() * 15 / orb.getCapacity();"

Being that it may be possible that "orb.getCapacity()" is returning 0, and thus, the return is dividing by zero.

Something like this should be implemented instead:

float capacity = orb.getCapacity();
if (capacity <= 0) {
    return 0;
}
return NetworkHelper.getSoulNetwork(binding).getCurrentEssence() * 15 / capacity;

I will note that the crash happens before the comparator is placed, and the crash actually prevents the comparator from being placed in the world.  The crash can be mitigated by placing the comparator first, then placing the bloodstone afterwards.

### PR DESCRIPTION
**Pull request by stellanera98**
fixes #2102

### CODE REVIEW

File: src/main/java/wayoftime/bloodmagic/altar/BloodAltar.java [hunk 1]
```diff
@@ -793,7 +796,12 @@ public int getAnalogSignalStrength(int redstoneMode)
 			if (binding == null || orb == null)
 				return 0;
 
-			return NetworkHelper.getSoulNetwork(binding).getCurrentEssence() * 15 / orb.getCapacity();
+            SoulNetwork network = NetworkHelper.getSoulNetwork(binding);
+            if (network == null)
+                return 0;
+
+            // see AbstractContainerMenu#getRedstoneSignalFromContainer
+            return Mth.floor((float) network.getCurrentEssence() / (float) orb.getCapacity() * 14.0F) + (network.getCurrentEssence() > 0 ? 1 : 0);
```
Comment (wrincewind) [inline src/main/java/wayoftime/bloodmagic/altar/BloodAltar.java]: this needs to be clamped to cap at a maximum output of 15 - if you put in an orb with a value lower than the soul network's fill level, you can end up with the comparator producing redstone signals >15.

**Review by wrincewind — CHANGES_REQUESTED** [review]

**Review by wrincewind — APPROVED** [review]
