### PR TITLE
Fix: Interaction Sigil of Holding + Seer/Divination Sigil (no render)

### LINKED ISSUE #1285: Interaction between the Divination Sigil, Sigil of Holding, and Blood Altar
Currently the Divination and Seer sigils cannot observe the LP inside of a Blood Altar when used in a Sigil of Holding. This should be remedied.

### PR DESCRIPTION
**Pull request by keraldi**
Seer Sigil and Sigil of Divination now work properly when placed inside the Sigil of Holding
(rendering not included)

closes #1285

### CODE REVIEW

File: src/main/java/WayofTime/bloodmagic/client/hud/element/ElementDivinedInformation.java [hunk 1]
```diff
@@ -25,22 +28,47 @@ public boolean shouldRender(Minecraft minecraft) {
...
+                flag = isFlagSigilHolding(sigilStack, true);
+
             if (!flag) {
                 sigilStack = player.getHeldItem(EnumHand.OFF_HAND);
                 if (sigilStack.getItem() == RegistrarBloodMagicItems.SIGIL_DIVINATION)
                     flag = true;
             }
+
+            if(!flag) {
+                flag = isFlagSigilHolding(sigilStack, true);
```
Comment (TehNut) [inline src/main/java/WayofTime/bloodmagic/client/hud/element/ElementDivinedInformation.java]: Move this to the if block above to make the logic flow clearer

File: src/main/java/WayofTime/bloodmagic/client/hud/element/ElementDivinedInformation.java [hunk 2]
```diff
@@ -25,22 +28,47 @@ public boolean shouldRender(Minecraft minecraft) {
...
+
             if (!flag) {
                 sigilStack = player.getHeldItem(EnumHand.OFF_HAND);
                 if (sigilStack.getItem() == RegistrarBloodMagicItems.SIGIL_SEER)
                     flag = true;
             }
-        }
 
+            if(!flag)
+                flag = isFlagSigilHolding(sigilStack, false);
```
Comment (TehNut) [inline src/main/java/WayofTime/bloodmagic/client/hud/element/ElementDivinedInformation.java]: Move this to the if block above to make the logic flow clearer

**Review by TehNut — CHANGES_REQUESTED** [review]

**Comment by keraldi** [comment]
Done.
